title:               Youngdo Kim
url:                 https://youngdo-kim.github.io/
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty
paginate:            5
paginate_path:       /Research/:num

Research:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             :compressed

author:
  name:              Youngdo Kim
  url:               youngdo-kim.github.io
  email:             youngdokim@postech.ac.kr

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
